config/routes.rb
Micropost::Application.routes.draw do
  get "home/index"
  devise_for :users
  resources :posts

  resources :users
  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up){|u| u.permit(:name, :location, :description, :email, :password) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :get_users
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
    
    def get_users
    @users = User.all.map {|user| [user.name, user.id]}
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :location, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flass_class(type)
    case type
    when :success then "success"
    when :error then "warning"
    when :alert then "warning"
    when :notice then ""
    else "info"
    end 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!--Banner Start-->
    <div id="banner">
      <ul id="home-banner">
        <li>  <%= image_tag "banner-1.jpg" %>
          <div class="caption">
            <div class="holder">
              <div class="holder">
              <h1>Consultoria<span> Ambiental</span> <span></span></h1>
              <strong class="title">especializada</strong> en cambiar</div>
          </div>
        </li>
        <li> <%= image_tag "banner-1.jpg" %>
          <div class="caption">
            <div class="holder">
              <h1>From <span>Poverty</span> to <span>Plenty</span></h1>
              <strong class="title">Let’s plant 200 garedens in this spring</strong> </div>
          </div>
        </li>
        <li> <%= image_tag "banner-1.jpg" %>
          <div class="caption">
            <div class="holder">
               <div class="holder">
              <h1>Consultoria<span> Ambiental</span> <span></span></h1>
              <strong class="title">especializada</strong> en cambiar</div>
          </div>
        </li>
        <li> <%= image_tag "banner-1.jpg" %>
          <div class="caption">
            <div class="holder">
               <div class="holder">
              <h1>Consultoria<span> Ambiental</span> <span></span></h1>
              <strong class="title">especializada</strong> en cambiar</div>
          </div>
        </li>
      </ul>
      <div id="bx-pager"> <a data-slide-index="0" href="" class="rollIn animated"><%= image_tag "banner-thumb-1.jpg" %></a> <a data-slide-index="1" href="" class="rollIn animated"><%= image_tag "banner-thumb-2.jpg" %></a> <a data-slide-index="2" href="" class="rollIn animated"><%= image_tag "banner-thumb-3.jpg" %></a> <a data-slide-index="3" href="" class="rollIn animated"><%= image_tag "banner-thumb-4.jpg" %></a> </div>
    </div>
    <!--Banner End--> 


<!--Main Start-->
  <div id="main" class="spacing"> 
    <!--Our Services Section Start-->
    <section class="our-services">
      <div class="container">
        <div class="generic-heading">
          <h2>Nuestros Servicios</h2>
          <strong class="title-line">Lo que estamos haciendo</strong> </div>
        <div class="row">
          <div class="span3">
            <div class="services-box">
              <div class="services-round"><a href="#" class="sprite-1"><i class="fa fa-camera-retro fa-lg"></i></a></div>
              <h3>Diseño y Construcción</h3>
              <strong class="title-text">Ejecución</strong> <p> Creación mantenimiento de Plantas de Tratamiento de Agua Potable, Aguas Residuales Industriales </p>
              <a href="how-we-work.html" class="readmore">Leer Más<i class="fa fa-arrow-right"></i></a> </div>
          </div>
          <div class="span3">
            <div class="services-box">
              <div class="services-round"><a href="#" class="sprite-2"><i class="fa fa-bolt"></i></a></div>
              <h3>Comercialización</h3>
              <strong class="title-text">Mercadeo </strong>
              <p>Ayudamos a su empresa a que escoga el mejor camino</p>
              <a href="how-we-work.html" class="readmore">Leer Más<i class="fa fa-arrow-right"></i></a> </div>
          </div>
          <div class="span3">
            <div class="services-box">
              <div class="services-round"><a href="#" class="sprite-3"><i class="fa fa-cog"></i></a></div>
              <h3>Consultoria </h3>
              <strong class="title-text">Espacializada </strong>
              <p>Nuestros expertos te ayudaran a orientar el mejor servicio de innovación ambiental
               </p>
              <a href="how-we-work.html" class="readmore">Leer Más<i class="fa fa-arrow-right"></i></a> </div>
          </div>
          <div class="span3">
            <div class="services-box">
              <div class="services-round"><a href="#" class="sprite-4"><i class="fa fa-lightbulb-o"></i></a></div>
              <h3>Asesoría Ambiental</h3>
              <strong class="title-text"> Innovación</strong>
              <p>Nuestra empresa dispondra de estrategía para la invovación ambiental de la empresa</p>
              <a href="how-we-work.html" class="readmore">Leer Más<i class="fa fa-arrow-right"></i></a> </div>
          </div>
        </div>
      </div>
    </section>
    <!--Our Services Section End--> 
    
    
             
    
  
           
          
   
    
   
    
    <!--Featured Video Section Start-->
    <section class="featured-video-box slide" id="slide1" data-slide="1" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="generic-heading">
          <h2>¿Qué es Innova Ambiente Ingenieria?</h2>
          <strong class="title-line">Algo de lo que hacemos</strong> </div>
        <div class="row-fluid">
          <div class="span7">
            <div class="featured-video-col">
              <iframe src="http://player.vimeo.com/video/26802834" style="width:100%; height:357px;"></iframe>
            </div>
          </div>
          <div class="span5">
            <div class="featured-video-text">
              <h3>Ver algunos Videos</h3>
              <strong class="title">Innova Ingenieria Ambiental</strong>
              <ul>
                <li>
                  <div class="frame"><a href="#"><img src="images/featured-video-img-1.jpg" alt="img"></a></div>
                  <div class="text-box">
                    <div class="number-round">1</div>
                    <strong class="title">Que es eco social y el desarrollo sostenible</strong>
                    <p></p>
                    <a href="#" class="readmore">Leer Más</a> </div>
                </li>
                <li>
                  <div class="frame"><a href="#"><img src="images/featured-video-img-2.jpg" alt="img"></a></div>
                  <div class="text-box">
                    <div class="number-round">2</div>
                    <strong class="title">Innovación Organizacional</strong>
                    <p></p>
                    <a href="#" class="readmore">Leer Más</a> </div>
                </li>
                <li>
                  <div class="frame"><a href="#"><img src="images/featured-video-img-3.jpg" alt="img"></a></div>
                  <div class="text-box">
                    <div class="number-round">3</div>
                    <strong class="title">Asesorias y Capacitación</strong>
                    <p></p>
                    <a href="#" class="readmore">Leer Más</a> </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--Featured Video Section End--> 
     
   
    <!--Home Testimonials Start-->
    <section class="home-testimonials">
      <div class="container">
        <ul id="home-textimonials-slider">
          <li>
            <div class="testimonials-box">
              <div class="testimonials-text"> <i class="fa fa-quote-right"></i>
                <p>Del ambiente de su empresa depende del planeta</p>
                
              </div>
              <div class="testimonials-frame"><img src="images/home-testimonials-img-1.jpg" alt="img"></div>
              <div class="client-box">
                <h4>Testimonios</h4>
                <strong class="title">Nuestro clientes están felices</strong> <a href="#" class="view">Leer mas</a> </div>
            </div>
          </li>
          <li>
            <div class="testimonials-box">
              <div class="testimonials-text"> <i class="fa fa-quote-right"></i>
                <p>Innovaciñon genero alternativas de innovación ambiental en mi empresa</p>
                <ul class="tags">
                  <li><a href="#">-Confucius,</a></li>
                  <li><a href="#">Chinese</a></li>
                  <li><a href="#">teacher,</a></li>
                  <li><a href="#">editor,</a></li>
                  <li><a href="#">politician,</a></li>
                  <li><a href="#">and philosopher</a></li>
                </ul>
              </div>
              <div class="testimonials-frame"><img src="images/home-testimonials-img-2.jpg" alt="img"></div>
              <div class="client-box">
                <h4>Testimonios</h4>
                <strong class="title">Nuestro clientes están felices</strong> <a href="#" class="view">Leer Más</a> </div>
            </div>
          </li>
          <li>
            <div class="testimonials-box">
              <div class="testimonials-text"> <i class="fa fa-quote-right"></i>
                <p></p>
                <ul class="tags">
                  <li><a href="#">-Confucius,</a></li>
                  <li><a href="#">Chinese</a></li>
                  <li><a href="#">teacher,</a></li>
                  <li><a href="#">editor,</a></li>
                  <li><a href="#">politician,</a></li>
                  <li><a href="#">and philosopher</a></li>
                </ul>
              </div>
              <div class="testimonials-frame"><img src="images/home-testimonials-img-1.jpg" alt="img"></div>
              <div class="client-box">
                <h4>Testimonios</h4>
                <strong class="title">Nuestro clientes están felices</strong> <a href="#" class="view">Leer Más</a> </div>
            </div>
          </li>
        </ul>
      </div>
    </section>
    <!--Home Testimonials End--> 
  </div>
  <!--Main End--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Innova Ambiente Ingeniería " %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300,700,600,800' rel='stylesheet' type='text/css'>
  </head>

  <body >
  <div id="wrapper"> 

    <header id="header"> 
    <!--Navigation Area Start-->
    <div class="navigation-box home-page">
      <div class="container"> <strong class="logo">

        <a href="/"> 

        <%= image_tag "logo_innova.png" %>

      </a></strong>
        <div class="top-bar-outer">
          <div class="bottom-row">
           
            <div class="donate-box">  <a href="#" class="btn-donate">Sign <span>Up</span></a> <a href="#" class="btn-donate">Login<span></span></a></div>
          </div>
          <div class="nav-box">
            <div class="navbar">
              <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
              <div class="nav-collapse collapse">
                <nav id="nav">
                  <ul>
                    <li class="active"><a href="index.html">Inicio</a></li>
                    <li><a href="about.html">Quiénes Somos</a></li>
                    <li><a href="where-we-work.html">Productos y Servicios</a>
                     
                    </li>
                    <li><a href="full-gallery.html">Distribuciones</a>
                      
                    </li>
                    <li><a href="event.html">Clientes</a>
                    
                    </li>
                    <li><a href="blog.html">Galería</a>
                      
                    </li>
                    <li><a href="crowed-funding.html">Contáctenos</a>
                      
                    </li>
                   
                  </ul>
                </nav>
              </div>
            </div>
           
          </div>
         
        </div>

      </div>
    </div>
    
    <!--Navigation Area End--> 
    
  </header>
  <!--Header End--> 

       <%= yield %>

     </div > 

    <!--Footer Start-->
  <footer id="footer"> 
    <!--Footer Section 2 Start-->
    <section class="footer-section-2">
      <div class="container">
        <div class="row-fluid">
          <div class="span4">
            <address class="contact-box">
            <strong class="title">Contáctenos</strong>
            <p>Innova Ambiente Ingeniería pensando en el bienestar eco-social y el Desarrollo Sostenible, se dedica a la consultoria especializada en materia ambiental.</p>
            <strong class="number"><span>Teléfono:</span>311 459 00 89</strong> <a href="mailto:" class="email"><span>E-mail:</span>dimameclaing@gmail.com</a> <strong class="number"><span>Dirección :</span>Bogotá, Colombia</strong>
            </address>
          </div>
          <div class="span4">
            <div class="latest-event-gallery">
              <h4>Galería de Fotografías</h4>
              <div class="gallery-box">
                <ul class="gallery">
                  <li><a href="images/events-gallery/event-gallet-img-1.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-1.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-2.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-2.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-3.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-3.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-4.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-4.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-5.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-5.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-6.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-6.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-7.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-7.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-8.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-8.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-9.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-9.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-10.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-10.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-11.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-11.jpg" alt="img" /></a></li>
                  <li><a href="images/events-gallery/event-gallet-img-12.jpg" data-rel="prettyPhoto[gallery1]"><img src="images/events-gallery/event-gallet-img-12.jpg" alt="img" /></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="span4">
            <form action="form-1.php" method="post" class="get-touch-form">
              <h4>Escribanos</h4>
              <ul>
                <li>
                  <input name="name" required pattern="[a-zA-Z ]+" type="text" placeholder="Name" class="get-touch-input">
                </li>
                <li>
                  <input name="email" required pattern="^[a-zA-Z0-9-\_.]+@[a-zA-Z0-9-\_.]+\.[a-zA-Z0-9.]{2,5}$" type="text" placeholder="E-mail" class="get-touch-input">
                </li>
                <li>
                  <textarea name="comment" required cols="10" rows="10" class="get-touch-textarea" placeholder="Comments"></textarea>
                </li>
                <li>
                  <input name="" type="submit" class="btn-send-message" value="Send message">
                </li>
              </ul>
            </form>
          </div>
        </div>
      </div>
    </section>
    <!--Footer Section 2 End--> 
    
    <!--Footer Top Section Start-->
    <section class="footer-top-section">
      <div class="container">
        <div class="row-fluid">
          <div class="span6">
            <div class="left"> <i class="fa fa-envelope"></i> <strong class="title">Recibe Nuestro Boletín Informativo</strong>
              <p>¿ Mantente actualizado sobre todo lo que pasa en Innova?</p>
            </div>
          </div>
          <div class="span6">
            <div class="right">
              <form action="#" class="subscribe-form">
                <input name="" type="text" class="subscribe-input" required>
                <input name="" type="submit" class="btn-signup" value="Sign up">
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--Footer Top Section End--> 
    
    
    <!--CopyRights Section Start-->
    <section class="copyrights-section">
      <div class="container">
        <ul class="footer-social">
          <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus-square"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
          <li><a href="#"><i class="fa fa-pinterest-square"></i></a></li>
        </ul>
        <strong class="copy">COPYRIGHT &copy; 2014  By <a href="http://crunchpress.com/" target="_blank" class="web">
          Innova Ambiente Ingeniería</a></strong> </div>
    </section>
    <!--CopyRights Section End--> 
  </footer>
  <!--Footer End--> 
</div>
<!--Wrapper End--> 
    <%= javascript_include_tag "application" %>
    <!--JQUERY Start--> 
<!--Jquery 1.11.1 Js--> 
<script src="assets/jquery.js"></script> 
<!--Bootstrap Js--> 
<script src="assets/bootstrap.js"></script> 
<!--Modernizr Js--> 
<script src="assets/modernizr.custom.97074.js"></script> 
<!--Recent News Posts Images Effect Js--> 
<script src="assets/jquery.hoverdir.js"></script> 
<!--Bx Slider Js--> 
<script src="assets/jquery.bxslider.js"></script> 
<!--Next Event Contdown Js--> 
<script src="assets/jquery.plugin.js"></script> 
<!--Next Event Contdown Js--> 
<script src="assets/jquery.countdown.js"></script> 
<!--Our Chrity Store JS--> 
<script src="assets/jquery.flexisel.js"></script> 
<!--Parallax Effect Js--> 
<script src="assets/jquery.stellar.min.js"></script> 
<!--Footer Map Js--> 
<script src="http://maps.google.com/maps/api/js?sensor=false"></script> 
<!--Pretty Photo Js--> 
<script src="assets/jquery.prettyPhoto.js"></script> 
<!-- Style Switcher --> 
<script type="text/javascript" src="assets/styleswitch.js"></script> 
<script type="text/javascript" src="assets/jquery.tabSlideOut.v1.3.js"></script> 
<!--Custom Js--> 
<script src="assets/custom.js"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, options_for_select(@users) %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: 'button'%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post, class: 'button' %> 

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<%= link_to 'New Post', new_post_path, class: 'button' %>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post), class: 'button' %> 

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: 'button'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class: 'button'%> |

app/views/users/index.html.erb
<h1>Listing users</h1>
<%= link_to 'New User', new_user_path, class: 'button' %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Location</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.location %></td>
        <td><%= user.description %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: 'button' %> 